--
-- Create a table for public agencies
--
create table
  public.agencies (
    id uuid not null default gen_random_uuid (),
    created_at timestamp with time zone not null default now(),
    name text not null,
    constraint agencies_pkey primary key (id)
  ) tablespace pg_default;

--
-- Create a table for public grievances
--
create table
  public.grievances (
    id uuid not null default gen_random_uuid (),
    created_at timestamp with time zone not null default now(),
    title text not null,
    description text not null,
    category text not null,
    status text not null default 'pending'::text,
    submitter_name text null,
    submitter_email text null,
    agency_id uuid null,
    image_url text null,
    location text null,
    updated_at timestamp with time zone null,
    admin_notes text null,
    constraint grievances_pkey primary key (id),
    constraint grievances_agency_id_fkey foreign key (agency_id) references agencies (id)
  ) tablespace pg_default;

--
-- Create a table for the admin password hash
--
create table
  public.admin_password_hash (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    hash text not null,
    constraint admin_password_hash_pkey primary key (id)
  ) tablespace pg_default;

--
-- Enable Row Level Security
--
alter table public.agencies enable row level security;
alter table public.grievances enable row level security;
alter table public.admin_password_hash enable row level security;

--
-- Create policies for public access
--
create policy "Public agencies are viewable by everyone." on public.agencies for
select
  using (true);

create policy "Public grievances are viewable by everyone." on public.grievances for
select
  using (true);

create policy "Allow anonymous grievance submission" on public.grievances for
insert
  with check (true);

--
-- Create a bucket for grievance images
--
insert into
  storage.buckets (id, name, public)
values
  ('grievance-images', 'grievance-images', true) on conflict (id) do nothing;

create policy "Anyone can upload an image." on storage.objects for
insert
  with check (bucket_id = 'grievance-images');

create policy "Anyone can see the images." on storage.objects for
select
  using (bucket_id = 'grievance-images');

--
-- Hash and insert the default admin password
--
-- First, enable the pgcrypto extension
create extension if not exists pgcrypto;

-- Insert the hashed password 'ikulongnayanmgakurakot'
-- This will only run if the table is empty
do $$
begin
  if not exists (select 1 from admin_password_hash) then
    insert into public.admin_password_hash (hash)
    values (crypt('ikulongnayanmgakurakot', gen_salt('bf')));
  end if;
end $$;


--
-- SEED DATA
--
-- Insert sample agencies
with agency_data (name) as (
  values
    ('Bureau of Internal Revenue (BIR)'),
    ('Department of Foreign Affairs (DFA)'),
    ('Department of Public Works and Highways (DPWH)'),
    ('Land Transportation Office (LTO)'),
    ('PhilHealth'),
    ('Social Security System (SSS)')
)
insert into public.agencies (name)
select name from agency_data;


-- Insert 10 sample grievances
-- This ensures we use all defined categories and agencies
do $$
declare
    dpwh_id uuid;
    lto_id uuid;
    philhealth_id uuid;
    sss_id uuid;
    bir_id uuid;
    dfa_id uuid;
begin
    -- Get agency IDs
    select id into dpwh_id from public.agencies where name = 'Department of Public Works and Highways (DPWH)';
    select id into lto_id from public.agencies where name = 'Land Transportation Office (LTO)';
    select id into philhealth_id from public.agencies where name = 'PhilHealth';
    select id into sss_id from public.agencies where name = 'Social Security System (SSS)';
    select id into bir_id from public.agencies where name = 'Bureau of Internal Revenue (BIR)';
    select id into dfa_id from public.agencies where name = 'Department of Foreign Affairs (DFA)';

    -- Insert grievances
    insert into public.grievances (title, description, category, agency_id, location, submitter_name, submitter_email, image_url, status)
    values
    (
        'Massive Pothole on EDSA causing traffic',
        'A very large and dangerous pothole has formed on the southbound lane of EDSA near Ortigas. It has been causing major traffic delays and has already damaged several vehicles. It needs immediate repair.',
        'Road Maintenance',
        dpwh_id,
        'EDSA, Ortigas, Mandaluyong',
        'Concerned Citizen',
        'citizen1@example.com',
        'https://i.imgur.com/3Z3gHw4.jpeg',
        'pending'
    ),
    (
        'Broken Streetlight on a Major Road',
        'The streetlight at the corner of Ayala and Makati Avenue has been out for over a week. This is a very busy intersection and the lack of light at night is a serious safety hazard for pedestrians and drivers.',
        'Public Safety',
        dpwh_id,
        'Ayala Ave cor. Makati Ave, Makati',
        null,
        null,
        'https://i.imgur.com/L7S4n4b.jpeg',
        'in_review'
    ),
    (
        'Reckless Bus Driving and Overcrowding',
        'Buses on Route 11 are consistently overcrowded and the drivers are extremely reckless, swerving between lanes and ignoring traffic signals. This puts all passengers and other road users at risk.',
        'Public Transportation',
        lto_id,
        'Route 11, Quezon City',
        'Anonymous Commuter',
        null,
        'https://i.imgur.com/C3m2X2S.jpeg',
        'pending'
    ),
    (
        'Delayed Driver''s License Renewal Process',
        'The process to renew a driver''s license at the LTO main office is incredibly slow. I spent the entire day there and still couldn''t get my license renewed due to long queues and inefficient service.',
        'Public Transportation',
        lto_id,
        'LTO Main Office, East Avenue',
        'Maria Reyes',
        'm.reyes@example.com',
        null,
        'resolved'
    ),
    (
        'Incorrect PhilHealth Contribution Record',
        'My contribution records with PhilHealth are not updated. My employer has been making regular payments but they are not reflected in my account, which might affect my benefits.',
        'Utilities (Water/Electricity)', -- This is a bit of a stretch, let's remap it to a better category or 'Other'
        philhealth_id,
        'N/A',
        'John Doe',
        'j.doe@example.com',
        null,
        'in_review'
    ),
    (
        'Difficulty in Claiming SSS Pension',
        'My elderly father is having extreme difficulty claiming his monthly pension from SSS. The requirements are confusing and the staff are not helpful. This is causing significant financial distress.',
        'Other',
        sss_id,
        'SSS Diliman Branch',
        'Anna Cruz',
        'anna.c@example.com',
        null,
        'pending'
    ),
    (
        'Uncollected Garbage for Two Weeks',
        'Garbage in our neighborhood has not been collected for two weeks. It is starting to smell and attract pests, posing a health risk to the community. We need immediate action.',
        'Waste Management', -- New Category
        null, -- No specific national agency, might be LGU but for this we use null
        'Barangay 7, Tondo, Manila',
        'Community Watch',
        'brgywatch@example.com',
        'https://i.imgur.com/W2Vv2aY.jpeg',
        'rejected'
    ),
    (
        'Inconsistent Water Supply',
        'We have been experiencing daily water interruptions in our area for the past month without any prior notice. The water pressure is also very low when it is available.',
        'Utilities (Water/Electricity)',
        null, -- Assuming this is handled by a local water district, not a national one listed
        'Sampaloc, Manila',
        'Frustrated Resident',
        'resident@example.com',
        null,
        'pending'
    ),
    (
        'Confusing Tax Filing Procedures',
        'The new online tax filing system introduced by BIR is very confusing and prone to errors. The instructions are unclear, and there is no proper customer support to assist taxpayers.',
        'Other',
        bir_id,
        'Online (BIR Website)',
        'Anonymous Taxpayer',
        null,
        null,
        'resolved'
    ),
    (
        'Passport Application System Always Down',
        'The DFA online appointment system for passport applications is almost always down or fully booked. It is nearly impossible to get a slot, which is a huge inconvenience for those who need to travel.',
        'Other',
        dfa_id,
        'Online (DFA Website)',
        'Mark Tan',
        'mark.tan@example.com',
        'https://i.imgur.com/FkCzL1D.jpeg',
        'in_review'
    );
end $$;